### PR TITLE
Add GitHub actions

### PR DESCRIPTION
**Pull request by ralphtheninja**
As per discussion, see https://github.com/moscajs/aedes-persistence-level/issues/21#issuecomment-700617781

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Will add badge in a sec.

**Comment by robertsLando** [comment]
Will review all PRs soon once I come back to my laptop :) thanks @ralphtheninja !

**Comment by ralphtheninja** [comment]
> Will review all PRs soon once I come back to my laptop :) thanks @ralphtheninja !

Sweet! No rush. I'll make another PR once these are in, tweaking README and package.json. Maybe we want to update the README so it has similar badges as the redis/mongodb plugins?

**Comment by ralphtheninja** [comment]
We should also bump all other dependencies.

**Comment by robertsLando** [comment]
> Maybe we want to update the README so it has similar badges as the redis/mongodb plugins? 

Sure! So just missing:

- Docs/badges
- Bumpe deps

**Review by robertsLando — APPROVED** [review]
lgtm

**Pull request merged**
