### PR TITLE
fix: fix queue ordering

### PR DESCRIPTION
**Pull request by seriousme**
Up until now packets were stored in Leveldb using keys like:
https://github.com/moscajs/aedes-persistence-level/blob/e8e15b8c9633e5ca68a5b35aebc118cb5021fac3/persistence.js#L284

This presents a serialization challenge when the queue holds more than a few items.
E.g. when the queue holds items with messageId 0-15 then `outgoingStream` will traverse the keys as:
```javascript
'outgoing-id:myclient:0',  
'outgoing-id:myclient:1',
'outgoing-id:myclient:10', 
'outgoing-id:myclient:11',
'outgoing-id:myclient:12', 
'outgoing-id:myclient:13',
'outgoing-id:myclient:14', 
'outgoing-id:myclient:15',
'outgoing-id:myclient:2',  
'outgoing-id:myclient:3',
'outgoing-id:myclient:4',  
'outgoing-id:myclient:5',
'outgoing-id:myclient:6',  
'outgoing-id:myclient:7',
'outgoing-id:myclient:8',  
'outgoing-id:myclient:9'
```

This PR will change this into:
```javascript
'outgoing-id:myclient:0000000000000000',  
'outgoing-id:myclient:0000000000000001',
'outgoing-id:myclient:0000000000000002',  
'outgoing-id:myclient:0000000000000003',
'outgoing-id:myclient:0000000000000004',  
'outgoing-id:myclient:0000000000000005',
'outgoing-id:myclient:0000000000000006',  
'outgoing-id:myclient:0000000000000007',
'outgoing-id:myclient:0000000000000008',  
'outgoing-id:myclient:0000000000000009',
'outgoing-id:myclient:0000000000000010', 
'outgoing-id:myclient:0000000000000011',
'outgoing-id:myclient:0000000000000012', 
'outgoing-id:myclient:0000000000000013',
'outgoing-id:myclient:0000000000000014', 
'outgoing-id:myclient:0000000000000015'
```
The values will remain untouched.

If however you had a few records in your existing leveldb (e.g. id 0-5) and then add new ones (e.g. 6-15) using the new padding then those existing records will only be processed after the new ones. 

Kind regards,
Hans

### CODE REVIEW

**Comment by seriousme** [comment]
ps:  do we need to escape semicolons in client identifiers as well ?
e.g. if someone submits `my:client:identifier` as identifier then it will work today but we run the risk on future edge cases. So my suggestion would be to remove that risk all together ;-)

Kind regards,
Hans

**Review by robertsLando — APPROVED** [review]
> ps: do we need to escape semicolons in client identifiers as well ?

Absolutely! Thanks. Changes looks good! :)

**Comment by seriousme** [comment]
> > ps: do we need to escape semicolons in client identifiers as well ?
> 
> Absolutely! Thanks. Changes looks good! :)
Done :-)

Kind regards,
Hans

**Comment by seriousme** [comment]
I'm working to reshuffle the key handling a bit as I missed one encoding :-(

**Review by robertsLando — APPROVED** [review]
LGTM

**Comment by robertsLando** [comment]
Can I merge this? @seriousme

**Comment by seriousme** [comment]
Yes, should be OK.

Kind regards,
Hans

**Pull request merged**
